### ISSUE TITLE
exception during gcab detection on Ubuntu 14.04

### ISSUE THREAD

**Issue by manxorist** [elmirjagudin/symstore#7]
```
$ python3 symstore/cab.py 
Traceback (most recent call last):
  File "symstore/cab.py", line 8, in <module>
    gi.require_version('GCab', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 79, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GCab not available
```
gcab is not available on Ubuntu 14.04

**Comment by elmirjagudin** [comment]
Fixed in https://github.com/elmirjagudin/symstore/commit/4dacfabbd88c306e450739d57e19ccaa94968737

Fixed scheduled to be included into version 0.2.4 release.
